apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quote-app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "quote-app.labels" . | nindent 4 }}
data:
  appsettings.json: |-
    {{- (tpl (.Files.Get "appsettings.json.tpl") .) | nindent 4 }}