global using AutoMapper;
global using Quotes.API.Extensions;
global using Quotes.API.Hal;
global using Quotes.API.Models;
global using Quotes.API.Entities;
global using Quotes.API.Repositories;
global using Quotes.API.Middlewares;
global using Quotes.API.Validators;
global using FluentValidation;
global using FluentValidation.AspNetCore;
global using ILogger = Serilog.ILogger;