{{- if .Values.secretStore.localk8.enable -}}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.secretStore.localk8.name }}
  labels: {{ - include "dapr-infra.labels" . | nindent 4 }}-secretstore
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: namespace
      value: {{ .Release.Namespace | quote }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets","component"]
  verbs: ["get", "watch", "list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dapr-secret-reader
  namespace: {{ .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
{{- end -}}