{{- if .Values.stateStore.redis.enable -}}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.stateStore.redis.name }}
  labels: {{- include "dapr-infra.labels" . | nindent 4 }}-stateredis
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.stateStore.redis.redisHost }}
  - name: enableTLS
    value: {{ .Values.stateStore.redis.enableTLS }}
  - name: actorStateStore
    value:  {{ .Values.stateStore.redis.actorStateStore }}
{{- end -}}