apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quote-api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "quote-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quote-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quote-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quote-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort | default .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ template "quote-api.fullname" . }}-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
              readOnly: false
            - name: ca-cert
              mountPath: /etc/ssl/certs/self-signed-ca.crt
              subPath: self-signed-ca.crt
              readOnly: true
            - name: tls-cert
              mountPath: /app/cert
              readOnly: true  
          volumes:
            - name: {{ template "quote-api.fullname" . }}-volume
              configMap:
                name: {{ template "quote-api.fullname" . }}
            - name: ca-cert
              configMap:
                name: {{ template "quote-api.certConfigmap" . }} 
                defaultMode: 420
            - name: tls-cert
              secret:
                secretName: {{ include "quote-api.fullname" . }}-tls       
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
